app:
  name: spark-sprint-boot
server:
  port: 8081
master:
  uri: local
spring:
  datasource:
    url: jdbc:h2:file:~/spark
    driverClassName: org.h2.Driver
    username: sa
    password: password

  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
  kafka:
    consumer:
      bootstrap-servers: localhost:29092
      auto-offset-reset: earliest
      group-id: my-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.whiteKnightz


springapacheSpark:
  kafka:
    topic: my-topic
    group-id: my-group

auto:
  create:
    topics:
      enable: true